config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root "blogs#index"
  resources :blogs do
    get :user_stats, on: :collection
  end
  namespace :api do
    namespace :v1 do
      resources :blogs
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  paginates_per 30
  has_many :comments, dependent: :destroy # assocations
  validates :title, :author_name, :description, presence: true # validations

  # callbacks
  after_commit :send_email
  after_destroy :log_destroy_action
  after_find do |blog|
    puts "--You have found an object!--"
  end

  private
  def send_email
    puts 'sending email'
  end

  def log_destroy_action
    puts 'Article destroyed'
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :blog
  validates :description, presence: true

  def comment_updated
    "Hello"
  end
end

app/controllers/api/api_controller.rb
module Api
  class ApiController < ActionController::Base
    def pagination(collection)
      {
        current_page: collection.current_page,
        next_page: collection.next_page,
        prev_page: collection.prev_page, # use collection.previous_page when using will_paginate
        total_pages: collection.total_pages,
        total_count: collection.total_count
      }
    end
  end
end

app/controllers/api/v1/blogs_controller.rb
module Api
  module V1
    class BlogsController < Api::ApiController
      before_action :set_blog, only: [:show, :update, :destroy]
      after_action :print
      skip_before_action :verify_authenticity_token

      # /api/v1/blogs
      def index
        @blogs = Blog.order(id: :asc).page(params[:page] || 1).includes(:comments)
        render json: {data: ActiveModelSerializers::SerializableResource.new(@blogs, each_serializer: ::V1::BlogSerializer, comments: true),
           meta: pagination(@blogs)}
        # Serialzer
      end

      def create
        @blog = Blog.new(blog_params)
        if @blog.save
          render json: {}, status: :created
        else
          render json: {errors: @blog.errors.full_messages}, status: :unprocessable_entity
        end
      end

      def show
        # @comments = @blog.comments
        render json: {data: ActiveModelSerializers::SerializableResource.new(@blog, serializer: ::V1::BlogSerializer, comments: true)}
      end

      def update
        if @blog.update(blog_params)
          render json: {}, status: :ok
        else
          render json: {errors: @blog.errors.full_messages}, status: :unprocessable_entity
        end
      end

      def destroy
        @blog.destroy
        render json: {}, status: :ok
      end

      private
      def blog_params
        params.require(:blog).permit(:author_name, :title, :description)
      end

      def set_blog
        puts "I have been invoked in set_blog method"
        @blog = Blog.find(params[:id])
      end

      def print
        puts "I have been invoked in print method"
      end
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  # Controller Filters ->
  # Filters are methods that are run "before", "after" or "around" a controller action.
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  after_action :print

  # adding a custom method.
  # Serialzer
  # Specs
  def list_all_blogs_comments
  end

  def index
    @blogs = Blog.all
    # Serialzer
  end

  def new
    @blog = Blog.new
  end

  def create
    @blog = Blog.new(blog_params)
    if @blog.save
      flash[:notice] = "Article was successfully created"
      redirect_to blogs_path
    else
      render 'new'
    end
  end

  def show
    @comments = @blog.comments
    render json: {data: ActiveModelSerializers::SerializableResource.new(@blog, serializer:BlogSerializer)}
  end

  def edit
  end

  def update
    if @blog.update(blog_params)
      flash[:notice] = "Article was successfully updated"
      redirect_to blog_path(params[:id])
    else
      render 'edit'
    end
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path
  end

  def user_stats
    @stats_hash = Blog.group(:author_name).count
  end

  private
  def blog_params
    params.require(:blog).permit(:author_name, :title, :description)
  end

  def set_blog
    puts "I have been invoked in set_blog method"
    @blog = Blog.find(params[:id])
  end

  def print
    puts "I have been invoked in print method"
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_for @blog do |f| %>
 <p>
  <%= f.label :title %><br>
  <%= f.text_field :title %>
 </p>
 <p>
  <%= f.label :description %><br>
  <%= f.text_area :description %>
 </p>
 <p>
  <%= f.label :author_name %><br>
  <%= f.text_field :author_name %>
 </p>
 <p>
  <%= f.submit %>
 </p>
<% end %>

app/views/blogs/edit.html.erb
<% if @blog.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @blog.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

<h1>Update an Article</h1>
<%= render 'form' %>

app/views/blogs/index.html.erb
<h1>Listing all Blog</h1>
<p>
<%= link_to "Create new Blog", new_blog_path %>
</p>
<table>
 <tr>
  <th>Title</th>
  <th>Description</th>
  <th>Author Name</th>
 </tr>
 <% @blogs.each do |blog| %>
 <tr>
  <td><%= blog.title %></td>
  <td><%= blog.description %></td>
  <td><%= blog.author_name %></td>
  <td><%= link_to 'Edit', edit_blog_path(blog) %></td>
  <td><%= link_to 'Show', blog_path(blog) %></td>
  <td><%= link_to 'Delete', blog_path(blog), method: :delete %></td>
 </tr>
 <% end %>
</table>

app/views/blogs/new.html.erb
<% if @blog.errors.any? %>
 <h2>The following errors prevented the article from saving:</h2>
 <ul>
 <% @blog.errors.full_messages.each do |msg|%>
 <li><%= msg %></li>
 <% end %>
 </ul>
<% end %>

<h1>Create an Article</h1>
<%= render partial: 'form' %>

app/views/blogs/show.html.erb
<h1>Showing selected blog</h1>
<p>
 Title: <%= @blog.title %>
</p>
<p>
 Description: <%= @blog.description %>
</p>
<p>
Author: <%= @blog.author_name %>
</p>
Comments: <% @comments.each do |comment| %>
<%= comment.description %>
<%end%>

app/views/blogs/user_stats.html.erb
<% @stats_hash.each do |k,v| %>
<%= "#{k} has #{v} blogs" %> <br>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BlogNew</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% flash.each do |name, msg| %>
        <ul>
         <li><%= msg %></li>
        </ul>
    <% end %>
    <%= yield %>
  </body>
</html>